# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_company',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
